In [15]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [16]:
df_sber_30 = pd.read_csv("..\\data\\order_books\\SBER_30.csv", header=0)
df_srh6_30 = pd.read_csv("..\\data\\order_books\\SRH6_30.csv", header=0)
df_srm6_30 = pd.read_csv("..\\data\\order_books\\SRM6_30.csv", header=0)
df_sru6_30 = pd.read_csv("..\\data\\order_books\\SRU6_30.csv", header=0)

In [17]:
df_sber_30

,TimeUtc,MidPriceClose,MidPriceAvg,MidPriceStdDev,SpreadAvg,Count
0,03/17/2026 06:42:30,316.115,316.115000,0.000000,0.010000,44
1,03/17/2026 06:43:00,316.235,316.213503,0.045844,0.044970,167
2,03/17/2026 06:43:30,316.235,316.233814,0.003546,0.012373,118
3,03/17/2026 06:44:00,316.340,316.302344,0.020893,0.026312,160
4,03/17/2026 06:44:30,316.335,316.332642,0.005982,0.021258,159
...,...,...,...,...,...,...
1075,03/17/2026 15:44:00,318.500,318.500000,0.000000,-1.000000,45
1076,03/17/2026 15:44:30,318.500,318.500000,0.000000,-1.000000,29
1077,03/17/2026 15:45:00,318.030,318.354138,0.217438,-0.683448,29
1078,03/17/2026 15:45:30,318.030,318.030000,0.000000,0.020000,16
1079,03/17/2026 15:46:00,318.030,318.030000,0.000000,0.020000,20

In [18]:
df_sru6_30

,TimeUtc,MidPriceClose,MidPriceAvg,MidPriceStdDev,SpreadAvg,Count
0,03/17/2026 06:42:30,31143.5,31143.500000,0.000000,39.000000,2
1,03/17/2026 06:43:00,31162.0,31155.972222,8.590702,28.314815,54
2,03/17/2026 06:43:30,31162.5,31162.236842,0.297729,24.473684,19
3,03/17/2026 06:44:00,31168.5,31167.152778,1.832649,34.305556,36
4,03/17/2026 06:44:30,31168.0,31166.868421,0.722607,33.736842,19
...,...,...,...,...,...,...
1061,03/17/2026 15:47:00,31362.0,31361.636364,0.222681,76.727273,11
1062,03/17/2026 15:47:30,31361.5,31361.750000,0.250000,76.500000,6
1063,03/17/2026 15:48:00,31362.5,31362.500000,0.000000,75.000000,11
1064,03/17/2026 15:48:30,31362.5,31363.812500,1.170937,72.375000,16
1065,03/17/2026 15:49:00,31361.5,31361.875000,0.360844,76.250000,12

In [19]:
df_srh6_30

,TimeUtc,MidPriceClose,MidPriceAvg,MidPriceStdDev,SpreadAvg,Count
0,03/17/2026 06:42:30,31650.0,31650.000000,0.000000,6.000000,44
1,03/17/2026 06:43:00,31662.0,31656.425000,4.574356,3.350000,140
2,03/17/2026 06:43:30,31665.5,31663.697368,1.480307,2.236842,38
3,03/17/2026 06:44:00,31671.5,31670.657025,2.141708,2.867769,121
4,03/17/2026 06:44:30,31672.5,31672.393258,0.680680,1.887640,89
...,...,...,...,...,...,...
1076,03/17/2026 15:47:30,31822.0,31822.517857,0.389187,5.178571,28
1077,03/17/2026 15:48:00,31823.5,31823.427273,0.551182,4.636364,55
1078,03/17/2026 15:48:30,31823.0,31824.347826,1.581836,3.594203,69
1079,03/17/2026 15:49:00,31822.5,31822.804878,0.243902,3.463415,41
1080,03/17/2026 15:49:30,31824.5,31825.112069,1.313206,3.982759,58