In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [5]:
df_sber = pd.read_csv("..\\data\\order_books_aggregated_SBER.csv", header=0)
sf_srh6 = pd.read_csv("..\\data\\order_books_aggregated_SRH6.csv", header=0)
sf_srm6 = pd.read_csv("..\\data\\order_books_aggregated_SRM6.csv", header=0)
sf_sru6 = pd.read_csv("..\\data\\order_books_aggregated_SRU6.csv", header=0)

In [6]:
df_sber

,TimeUtc,MidPriceClose,MidPriceAvg,MidPriceStdDev,SpreadAvg,Count
0,03/17/2026 06:42:30,316.115,316.115000,0.000000,0.010000,44
1,03/17/2026 06:43:00,316.235,316.213503,0.045844,0.044970,167
2,03/17/2026 06:43:30,316.235,316.233814,0.003546,0.012373,118
3,03/17/2026 06:44:00,316.340,316.302344,0.020893,0.026312,160
4,03/17/2026 06:44:30,316.335,316.332642,0.005982,0.021258,159
...,...,...,...,...,...,...
801,03/17/2026 13:23:00,318.505,318.505000,0.000000,0.010000,173
802,03/17/2026 13:23:30,318.495,318.503401,0.003642,0.010068,147
803,03/17/2026 13:24:00,318.515,318.502752,0.005532,0.010000,258
804,03/17/2026 13:24:30,318.590,318.555661,0.030896,0.014310,174
805,03/17/2026 13:25:00,318.575,318.584416,0.006029,0.010649,77

In [7]:
sf_sru6

,TimeUtc,MidPriceClose,MidPriceAvg,MidPriceStdDev,SpreadAvg,Count
0,03/17/2026 06:42:30,31143.5,31143.500000,0.000000,39.000000,2
1,03/17/2026 06:43:00,31162.0,31155.972222,8.590702,28.314815,54
2,03/17/2026 06:43:30,31162.5,31162.236842,0.297729,24.473684,19
3,03/17/2026 06:44:00,31168.5,31167.152778,1.832649,34.305556,36
4,03/17/2026 06:44:30,31168.0,31166.868421,0.722607,33.736842,19
...,...,...,...,...,...,...
830,03/17/2026 13:47:00,31364.5,31364.500000,0.000000,23.000000,23
831,03/17/2026 13:47:30,31364.5,31364.500000,0.000000,23.000000,12
832,03/17/2026 13:48:00,31365.0,31364.631579,0.220174,23.263158,19
833,03/17/2026 13:48:30,31364.5,31364.575000,0.178536,23.150000,20
834,03/17/2026 13:49:00,31364.5,31364.500000,0.000000,23.000000,8

In [9]:
sf_srh6

,TimeUtc,MidPriceClose,MidPriceAvg,MidPriceStdDev,SpreadAvg,Count
0,03/17/2026 06:42:30,31650.0,31650.000000,0.000000,6.000000,44
1,03/17/2026 06:43:00,31662.0,31656.425000,4.574356,3.350000,140
2,03/17/2026 06:43:30,31665.5,31663.697368,1.480307,2.236842,38
3,03/17/2026 06:44:00,31671.5,31670.657025,2.141708,2.867769,121
4,03/17/2026 06:44:30,31672.5,31672.393258,0.680680,1.887640,89
...,...,...,...,...,...,...
845,03/17/2026 13:48:00,31865.5,31864.419048,1.236592,2.419048,105
846,03/17/2026 13:48:30,31864.5,31865.180233,0.702623,1.593023,86
847,03/17/2026 13:49:00,31864.5,31864.500000,0.000000,1.000000,53
848,03/17/2026 13:49:30,31864.5,31864.500000,0.000000,1.000000,39
849,03/17/2026 13:50:00,31868.5,31867.170213,1.255950,2.042553,47